### ISSUE TITLE
docker-compose up 报错

### ISSUE THREAD

**Issue by BigHoneyBadger** [voocel/docker-lnmp#10]
**configure: error: Please reinstall the libzip distribution**
**ERROR: Service 'php' failed to build:** The command '/bin/sh -c set -x   && yum update -y   && yum install epel-release -y   && yum install -y wget git gcc gcc-c++ make automake autoconf perl file tar re2c libjpeg libpng libjpeg-devel libpng-devel libjpeg-turbo freetype freetype-devel         libcurl-devel libxml2-devel libjpeg-turbo-devel libXpm-devel libXpm libicu-devel libmcrypt libmcrypt-devel libxslt-devel libxslt openssl openssl-devel bzip2-devel   && mkdir ~/download   && cd ~/download   && wget http://cn2.php.net/distributions/php-$PHP_VERSION.tar.gz   && tar -zxf php-$PHP_VERSION.tar.gz   && cd php-$PHP_VERSION   && groupadd -r nginx   && useradd -r -g nginx nginx   && ./configure        --prefix=/usr/local/php        --with-config-file-path=/usr/local/php/etc/        --with-config-file-scan-dir=/usr/local/php/conf.d/        --enable-fpm        --enable-cgi        --with-fpm-user=nginx         --with-fpm-group=nginx        --disable-phpdbg        --enable-mbstring        --enable-calendar        --with-xsl        --with-openssl        --enable-soap        --enable-zip        --enable-shmop        --enable-sockets        --with-gd        --with-freetype-dir=/usr/include/freetype2/freetype        --with-jpeg-dir        --with-png-dir        --with-xpm-dir        --with-xmlrpc        --enable-pcntl        --enable-intl        --with-mcrypt        --enable-sysvsem        --enable-sysvshm        --enable-sysvmsg        --enable-opcache        --with-iconv        --with-bz2        --with-curl        --enable-mysqlnd        --with-mysqli=mysqlnd        --with-pdo-mysql=mysqlnd        --with-zlib        --with-gettext   && make   && make install   && cp ~/download/php-$PHP_VERSION/php.ini-production /usr/local/php/etc/php.ini   && cp /usr/local/php/etc/php-fpm.conf.default /usr/local/php/etc/php-fpm.conf   && cp /usr/local/php/etc/php-fpm.d/www.conf.default /usr/local/php/etc/php-fpm.d/www.conf   && cd ~/download   && wget https://github.com/phpredis/phpredis/archive/$REDIS_VERSION.tar.gz   && tar -zxvf $REDIS_VERSION.tar.gz   && cd phpredis-$REDIS_VERSION   && /usr/local/php/bin/phpize   && ./configure --with-php-config=/usr/local/php/bin/php-config   && make   && make install   && echo "export PATH=/usr/local/php/bin:/usr/local/php/sbin:$PATH" >> ~/.bashrc   && source ~/.bashrc   && cd ~/download   && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"   && php composer-setup.php --install-dir=/usr/local/sbin --filename=composer   && php -r "unlink('composer-setup.php');"   && rm -rf ~/download   && yum clean all' returned a non-zero code: 1
没有找到libzip
请重新安装libzip的dev包。

**Comment by BigHoneyBadger** [comment]
php exited with code 78
php      | [17-Sep-2019 20:01:04] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:01:04] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:04] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:04] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:01:04] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:01:08] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:01:11] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:11] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:11] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:01:11] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:01:40] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:01:46] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:46] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:01:46] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:01:46] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:03] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:03] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:03] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:03] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:03] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:06] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:08] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:08] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:08] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:08] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:20] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:22] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:22] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:22] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:22] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:28] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:29] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:29] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:29] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:29] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:38] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:39] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:39] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:39] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:39] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:47] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:02:50] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:50] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:02:50] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:02:50] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:01] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:03:01] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:01] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:01] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:01] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:16] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:03:18] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:18] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:18] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:18] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:48] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:03:48] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:48] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:03:48] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:03:48] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:04:42] NOTICE: PHP message: PHP Warning:  Module 'swoole' already loaded in Unknown on line 0
php      | [17-Sep-2019 20:04:44] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:04:44] ERROR: [pool www] cannot get uid for user 'git'
php      | [17-Sep-2019 20:04:44] ERROR: FPM initialization failed
php      | [17-Sep-2019 20:04:44] ERROR: FPM initialization failed

**Comment by voocel** [comment]
可以将配置文件www.conf里的
```
user = git
group = git
```
改成 
```
user = www-data
group = www-data
```
