### ISSUE TITLE
up还是报错

### ISSUE THREAD

**Issue by BigHoneyBadger** [voocel/docker-lnmp#11]
Removing intermediate container 55e335d90233
Step 5/5 : RUN cd ~     && adduser -s /bin/bash git -D -H     && wget https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz     && tar -zxvf $PHPREDIS_VERSION.tar.gz     && mkdir -p /usr/src/php/ext     && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis     && docker-php-ext-install redis     && apk add libstdc++ libpng-dev     && cd ~     && wget https://github.com/swoole/swoole-src/archive/v$SWOOLE_VERSION.tar.gz     && tar -zxvf v$SWOOLE_VERSION.tar.gz     && mkdir -p /usr/src/php/ext     && mv swoole-src-$SWOOLE_VERSION /usr/src/php/ext/swoole     && docker-php-ext-install swoole     && docker-php-ext-install pdo_mysql mysqli pcntl gd    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer
 ---> Running in 9f8c24a57e91

container_linux.go:235: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""
ERROR: Service 'php' failed to build: oci runtime error: container_linux.go:235: starting container process caused "process_linux.go:258: applying cgroup configuration for process caused \"Cannot set property TasksAccounting, or unknown property.\""

**Comment by voocel** [comment]
应该是系统版本过低, 需要升级
