### ISSUE TITLE
PHP安装swoole扩展

### ISSUE THREAD

**Issue by lyx554073858** [voocel/docker-lnmp#7]
在版本v1中如何安装php的swoole扩展呢

**Comment by voocel** [comment]
同样可以同v2版本那般安装，也可以自己源码编译安装

**Comment by lyx554073858** [comment]
我在V1版本中使用V2版本安装swoole试了下不行，后来用如下方式安装就可以了：
  # 安装 Swoole
  && yum install -y  libstdc++ libpng-dev \
  && cd ~/download \
  && wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz \
  && tar -zxvf $SWOOLE_VERSION.tar.gz \
  && mkdir -p /usr/src/php/ext \
  
  # 当swoole版本不一致时，需要进行修改)
  && mv swoole-src-4.2.12 /usr/src/php/ext/swoole \
  && cd /usr/src/php/ext/swoole \
  # && phpize \
  && /usr/local/php/bin/phpize \  
  # && ./configure \
  &&./configure --with-php-config=/usr/local/php/bin/php-config \
  && make \
  && make install \
  # && docker-php-ext-install swoole \

**Comment by voocel** [comment]
因为v1版本用的发行版是CentOS,v2版本是用的alpine,所以包管理工具是不一样的

**Comment by lyx554073858** [comment]
是的，大神方便加个QQ或者微信么，向你学习学习
